sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
apt:
  packages:
    - dpkg  # see https://github.com/travis-ci/travis-ci/issues/9361
addons:
  chrome: stable
before_install:
  - sudo apt-get clean
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - sudo apt-get install --reinstall dpkg
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - google-chrome --version
  - mkdir travis-bin
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
#  - ls -l $PWD/travis-bin
#  - chromedriver --version
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
script:
  - mvn clean cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml
  - bash <(curl -s https://codecov.io/bash)