sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - mkdir travis-bin
  - wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip -O $PWD/travis-bin/chromedriver_linux64.zip
  - unzip $PWD/travis-bin/chromedriver_linux64.zip -d $PWD/travis-bin
  - export PATH=$PWD/travis-bin:$PATH
#  - ls -l $PWD/travis-bin
#  - chromedriver --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - mvn clean cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml
  - bash <(curl -s https://codecov.io/bash)