name: Java-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Chrome
        run: sudo apt install google-chrome-stable
      - name: Install Chromedriver
        run: |
          mkdir github-bin
          wget https://chromedriver.storage.googleapis.com/92.0.4515.43/chromedriver_linux64.zip -O $PWD/github-bin/chromedriver_linux64.zip
          unzip $PWD/github-bin/chromedriver_linux64.zip -d $PWD/github-bin
          export PATH=$PWD/github-bin:$PATH
      - name: Test with Maven
        run: mvn clean test
      - name: Generate coverage with Maven
        run: mvn clean cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml
      - name: Publish coverage
        run: bash <(curl -s https://codecov.io/bash)