name: Java-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Chrome
        run: sudo apt install google-chrome-stable
      - name: Install Chromedriver
        run: |
          mkdir github-bin
          wget https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_linux64.zip -O $PWD/github-bin/chromedriver_linux64.zip
          unzip $PWD/github-bin/chromedriver_linux64.zip -d $PWD/github-bin
          export PATH=$PWD/github-bin:$PATH
      - name: Test and generate coverage with Maven
        run: mvn clean verify surefire-report:report-only -Daggregate=true
      - name: Publish coverage
        run: bash <(curl -s https://codecov.io/bash) -f plugin-parent/coverage/target/site/jacoco-aggregate/jacoco.xml